---
title: "Data visualization.Rmd"
author: "Anja Sørensen"
date: "17/6/2021"
output: html_document
---
### 11.3 Graph individual variables

```{r setup}
# Load packages
source(here::here("R/package-loading.R"))

# Load the small, tidied dataset from the wrangling session
load(here::here("data/nhanes_small.rda"))
```

# One variable plots
```{r continuous-variable}
ggplot(nhanes_small, aes(x = bmi)) +
    geom_density()

ggplot(nhanes_small, aes(x = bmi)) +
    geom_histogram()
```

```{r discrete-variables}
ggplot(nhanes_small, aes(x = sex)) +
    geom_bar()

ggplot(nhanes_small, aes(x = diabetes)) +
    geom_bar()

# Removing NAs
nhanes_small %>% 
    drop_na(diabetes) %>% 
    ggplot(aes(x = diabetes)) +
    geom_bar()
```
```{r remove missing diabetes answer, aka the NAs}
nhanes_tidy<- nhanes_small %>% 
    filter(!is.na(diabetes))

usethis::use_data(nhanes_tidy, overwrite = TRUE)

ggplot(nhanes_tidy, aes(x = diabetes)) +
    geom_bar()
```
# Plotting two variables
```{r Two-continuous-variables}
bmi_chol<- ggplot(nhanes_tidy, aes(x = bmi, y = tot_chol))
bmi_chol +
    geom_point()

bmi_chol +
    geom_hex()

bmi_chol +
    geom_smooth()

bmi_chol +
    geom_hex() +
    geom_smooth()
```
```{r Two-discrete-variables}
two_discrete<- nhanes_tidy %>%
    ggplot(aes(x = diabetes, fill = sex))

two_discrete +
    geom_bar()

two_discrete +
    geom_bar(position = position_dodge())
    
```
```{r discrete-continuous-variables}
two_mixed<- nhanes_tidy %>% 
    ggplot(aes(x = diabetes, y = bmi))

two_mixed +
    geom_boxplot()

two_mixed +
    geom_jitter()

two_mixed +
    geom_violin()
```

### 11.5 Exercise: Creating plots with one or two variables
```{r exercise}
# 1a. Distribution of age
ggplot(nhanes_tidy, aes(x = age)) +
    geom_histogram()
    
# 1b. Distribution of age of diabetes diagnosis
ggplot(nhanes_tidy, aes(x = diabetes_age)) +
    geom_histogram()

# 2a. Number of people who smoke now
ggplot(nhanes_tidy, aes(x = smoke_now)) +
    geom_bar()

# 2b. Number of people who are physically active
ggplot(nhanes_tidy, aes(x = phys_active)) +
    geom_bar()

# 3a. BMI in relation to systolic blood pressure
ggplot(nhanes_tidy, aes(x = bmi, y = bp_sys_ave)) +
    geom_hex()

# 3b. BMI relation to diastolic blood pressure
ggplot(nhanes_tidy, aes(x = bmi, y = bp_dia_ave)) +
    geom_hex()
    
# 4. Physically active people with or without diabetes
ggplot(nhanes_tidy, aes(x = diabetes, fill = phys_active)) +
    geom_bar(position = position_dodge())

# 5. Poverty levels between those with or without diabetes
ggplot(nhanes_tidy, aes(x = diabetes, y = poverty)) +
    geom_violin()
```
### 11.6 Visualizing three or more variables

```{r using-colour}
# 1 continuous variables and 2 discrete variables
nhanes_tidy %>% 
    ggplot(aes(x = sex, y = bp_sys_ave, colour = diabetes)) +
    geom_boxplot()

# Three continuous variables
nhanes_tidy %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point()

# Two continuous and 1 discrete variable
nhanes_tidy %>% 
    ggplot(aes(x =bmi, y = bp_sys_ave, colour = diabetes)) +
    geom_point()

```
```{r using-faceting}
# Side-by-side - cols
nhanes_tidy %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) +
    geom_point() +
    facet_grid(cols = vars(diabetes))
# Stacked - rows
nhanes_tidy %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) +
    geom_point() +
    facet_grid(rows = vars(diabetes))

# Five variables
nhanes_tidy %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point() +
    facet_grid(rows = vars(diabetes), 
               cols = vars(sex))
```
###11.8 Exercise: Changing the colour scheme
```{r exercise-discrete-variables-viridis}
# Barplot to work from, with two discrete variables
base_barplot <- nhanes_tidy %>% 
    ggplot(aes(x = diabetes, fill = sex)) +
    geom_bar(position = position_dodge())

# Using viridis_d when discrete, otherwise, _c
base_barplot +
    scale_fill_viridis_d(option = "E")

# Scatterplot to work from, with three continuous variables
base_scatterplot <- nhanes_tidy %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point()

base_scatterplot +
    scale_color_viridis_c(option = "B")
```
# 11.9 Titles, axis labels, and themes
```{r build-in-themes}
# Create scatterplot to play with themes
base_scatterplot2 <- base_scatterplot +
    facet_grid(rows = vars(diabetes),
               cols = vars(sex)) +
    scale_color_viridis_c()

# View the plot with the default theme
base_scatterplot2

# Test out some pre-defined themes
base_scatterplot2 + 
    theme_bw()

base_scatterplot2 +
    theme_minimal()

base_scatterplot2 +
    theme_dark()

# Set the theme for all plot. 
# Start the session with this - in the future
theme_set(theme_bw())

# Change the title and labels
base_scatterplot2 +
    labs(title = "BMI, Sys.BP and Age by Diabetes status and Sex",
         y = "Systolic blood pressure (mmHg)",
         x = "BMI (kg/m2)")
```
# Saving the plots
```{r}
ggsave(here::here("doc/images/scatterplot.pdf"), 
       base_scatterplot2, width = 7, height = 5)
```

